
package createaccountproxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "createAccountPortType", targetNamespace = "http://soprabanking.com/amplitude")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreateAccountPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns createaccountproxy.GetStatusResponseFlow
     * @throws ErrorResponseFlow_Exception
     */
    @WebMethod(action = "getStatus")
    @WebResult(name = "getStatusResponseFlow", targetNamespace = "http://soprabanking.com/amplitude", partName = "parameters")
    public GetStatusResponseFlow getStatus(
        @WebParam(name = "getStatusRequestFlow", targetNamespace = "http://soprabanking.com/amplitude", partName = "parameters")
        GetStatusRequestFlow parameters)
        throws ErrorResponseFlow_Exception
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns createaccountproxy.CreateAccountResponseFlow
     * @throws ErrorResponseFlow_Exception
     */
    @WebMethod(action = "createAccount")
    @WebResult(name = "createAccountResponseFlow", targetNamespace = "http://soprabanking.com/amplitude", partName = "parameters")
    public CreateAccountResponseFlow createAccount(
        @WebParam(name = "createAccountRequestFlow", targetNamespace = "http://soprabanking.com/amplitude", partName = "parameters")
        CreateAccountRequestFlow parameters)
        throws ErrorResponseFlow_Exception
    ;

}
