
package createaccountproxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */

// Dev
// file:C:\Users\dkone\Documents\DEMATER\AppDM\Amplitude\createAccount_1.wsdl

// Test interne
// file:/home/admin/BDU_PROJECT/AAM/BACK/Amplitude/createAccount_1.wsdl

// Test
// file:C:\DEMATER\AppDM\Amplitude\createAccount_1.wsdl

// Preprod
// file:C:\DEMATER\AppDM\PRE-PROD\BACK\Amplitude\createAccount_1.wsdl

@WebServiceClient(name = "createAccount", targetNamespace = "http://soprabanking.com/amplitude", wsdlLocation = "file:/home/admin/BDU_PROJECT/AAM/BACK/Amplitude/createAccount_1.wsdl")
public class CreateAccount
    extends Service
{
    private final static URL CREATEACCOUNT_WSDL_LOCATION;
    private final static WebServiceException CREATEACCOUNT_EXCEPTION;
    private final static QName CREATEACCOUNT_QNAME = new QName("http://soprabanking.com/amplitude", "createAccount");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/admin/BDU_PROJECT/AAM/BACK/Amplitude/createAccount_1.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREATEACCOUNT_WSDL_LOCATION = url;
        CREATEACCOUNT_EXCEPTION = e;
    }

    public CreateAccount() {
        super(__getWsdlLocation(), CREATEACCOUNT_QNAME);
    }

    public CreateAccount(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREATEACCOUNT_QNAME, features);
    }

    public CreateAccount(URL wsdlLocation) {
        super(wsdlLocation, CREATEACCOUNT_QNAME);
    }

    public CreateAccount(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREATEACCOUNT_QNAME, features);
    }

    public CreateAccount(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreateAccount(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreateAccountPortType
     */
    @WebEndpoint(name = "createAccountPortType")
    public CreateAccountPortType getCreateAccountPortType() {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "createAccountPortType"), CreateAccountPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreateAccountPortType
     */
    @WebEndpoint(name = "createAccountPortType")
    public CreateAccountPortType getCreateAccountPortType(WebServiceFeature... features) {
        return super.getPort(new QName("http://soprabanking.com/amplitude", "createAccountPortType"), CreateAccountPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREATEACCOUNT_EXCEPTION!= null) {
            throw CREATEACCOUNT_EXCEPTION;
        }
        return CREATEACCOUNT_WSDL_LOCATION;
    }

}
