app:
  process-engine:
    datasource:
      url: jdbc:postgresql://localhost:5432/camundadmdb

      username: postgres
      password: postgres
#      username: postgres
#      password: postgres
      driver-class-name: org.postgresql.Driver
  dm-file:
    datasource:
      url: jdbc:postgresql://localhost:5432/dmdb
      username: postgres
      password: postgres
#      username: postgres
#      password: postgres
      driver-class-name: org.postgresql.Driver
  file-storage:
    template-base-path: /home/admin/BDU_PROJECT/AAM/BACK/Contrat_Templates/
    datasource:
      url: jdbc:postgresql://localhost:5432/dmfiledb
      username: postgres
      password: postgres
#      username: postgres
#      password: postgres
      driver-class-name: org.postgresql.Driver
  configuration:
    uploadBasePath: /home/admin/BDU_PROJECT/AAM/

keycloak:
  realm: BOX.AFRICA
  resource: lam-front
# auth-server-url: http://23.97.188.156:8080/auth
  auth-server-url: http://40.40.40.107:8080/auth
  ssl-required: none #external
  confidential-port: 0
  public-client: false
  cors: true
  #enabled : false
  #bearer-only: true
  credentials:
    secret: 25362efe-4112-45e6-9c2b-6e4c70ac13c5
amplitude:
  soap-path: file:/home/admin/BDU_PROJECT/AAM/BACK/Amplitude/