CREATE TABLE IF NOT EXISTS roles (
    id                      INT8 NOT NULL PRIMARY KEY,
    name                    VARCHAR(255) NOT NULL UNIQUE,
    created_timestamp       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE SEQUENCE roles_id_seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
ALTER TABLE roles ADD CONSTRAINT UC_roles_name UNIQUE (name);