CREATE TABLE IF NOT EXISTS settings (
    id                      INT8 NOT NULL PRIMARY KEY,
    name                    VARCHAR(255) NOT NULL UNIQUE,
    value                   VARCHAR(255) NOT NULL,
    created_timestamp       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_timestamp       TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE SEQUENCE settings_id_seq MINVALUE 1 START WITH 1 INCREMENT BY 1;
ALTER TABLE settings ADD CONSTRAINT UC_settings_name UNIQUE (name);
