INSERT INTO categorie_professionnelle (id, code, name)
VALUES
    (nextval('categorie_professionnelle_id_seq'), 'ARC', 'ARCHITECTE'),
    (nextval('categorie_professionnelle_id_seq'), 'ART', 'ARTISAN'),
    (nextval('categorie_professionnelle_id_seq'), '999', 'PROF de la REPRISE'),
    (nextval('categorie_professionnelle_id_seq'), 'ADM', 'ADMINISTRATEUR'),
    (nextval('categorie_professionnelle_id_seq'), 'AGB', 'AGENT DE BANQUE'),
    (nextval('categorie_professionnelle_id_seq'), 'AGR', 'AGRICULTEUR'),
    (nextval('categorie_professionnelle_id_seq'), 'AJU', 'AJUSTEUR'),
    (nextval('categorie_professionnelle_id_seq'), 'ANA', 'ANALYSTE'),
    (nextval('categorie_professionnelle_id_seq'), 'ASM', 'ASSISTANT MEDICAL'),
    (nextval('categorie_professionnelle_id_seq'), 'AVO', 'AVOCAT'),
    (nextval('categorie_professionnelle_id_seq'), 'BAR', 'BARBIER'),
    (nextval('categorie_professionnelle_id_seq'), 'BOU', 'BOUCHER'),
    (nextval('categorie_professionnelle_id_seq'), 'BQE', 'BANQUIER'),
    (nextval('categorie_professionnelle_id_seq'), 'CAI', 'CAISSIER'),
    (nextval('categorie_professionnelle_id_seq'), 'CHA', 'CHARCUTIER'),
    (nextval('categorie_professionnelle_id_seq'), 'CHF', 'CHAUFFEUR'),
    (nextval('categorie_professionnelle_id_seq'), 'COI', 'COIFFEUR'),
    (nextval('categorie_professionnelle_id_seq'), 'COM', 'COMMERCANT'),
    (nextval('categorie_professionnelle_id_seq'), 'CPT', 'COMPTABLE'),
    (nextval('categorie_professionnelle_id_seq'), 'DAC', 'DACTYLOGRAPHE'),
    (nextval('categorie_professionnelle_id_seq'), 'DET', 'Commercant detaillant'),
    (nextval('categorie_professionnelle_id_seq'), 'DGR', 'Commercant demi_grossiste'),
    (nextval('categorie_professionnelle_id_seq'), 'DIV', 'divers'),
    (nextval('categorie_professionnelle_id_seq'), 'DOU', 'DOUANIER'),
    (nextval('categorie_professionnelle_id_seq'), 'ECO', 'ECONOMISTE'),
    (nextval('categorie_professionnelle_id_seq'), 'ELE', 'ELEVEUR'),
    (nextval('categorie_professionnelle_id_seq'), 'EMP', 'EMPLOYE'),
    (nextval('categorie_professionnelle_id_seq'), 'ENS', 'ENSEIGNANT'),
    (nextval('categorie_professionnelle_id_seq'), 'ENT', 'ENTREPRENEUR'),
    (nextval('categorie_professionnelle_id_seq'), 'ETU', 'ETUDIANT'),
    (nextval('categorie_professionnelle_id_seq'), 'FER', 'FERMIER'),
    (nextval('categorie_professionnelle_id_seq'), 'FON', 'FONCTIONNAIRE'),
    (nextval('categorie_professionnelle_id_seq'), 'GAR', 'GARAGISTE'),
    (nextval('categorie_professionnelle_id_seq'), 'GED', 'GENDARME'),
    (nextval('categorie_professionnelle_id_seq'), 'IND', 'INDUSTRIEL'),
    (nextval('categorie_professionnelle_id_seq'), 'INF', 'INFORMATICIEN'),
    (nextval('categorie_professionnelle_id_seq'), 'ING', 'INGENIEUR'),
    (nextval('categorie_professionnelle_id_seq'), 'INR', 'INFIRMIER'),
    (nextval('categorie_professionnelle_id_seq'), 'IPJ', 'INSPECTEUR DE POLICE JUDICIAIR'),
    (nextval('categorie_professionnelle_id_seq'), 'JOU', 'JOURNALISTE'),
    (nextval('categorie_professionnelle_id_seq'), 'JUG', 'JUGE'),
    (nextval('categorie_professionnelle_id_seq'), 'KIN', 'KINESITHERAPEUTE'),
    (nextval('categorie_professionnelle_id_seq'), 'LAB', 'LABORATIN'),
    (nextval('categorie_professionnelle_id_seq'), 'MAC', 'MACON'),
    (nextval('categorie_professionnelle_id_seq'), 'MAG', 'MAGASINIER'),
    (nextval('categorie_professionnelle_id_seq'), 'MEC', 'MECANICIEN'),
    (nextval('categorie_professionnelle_id_seq'), 'MED', 'MEDECIN'),
    (nextval('categorie_professionnelle_id_seq'), 'MEN', 'MENUISIER'),
    (nextval('categorie_professionnelle_id_seq'), 'MIL', 'MILITAIRE'),
    (nextval('categorie_professionnelle_id_seq'), 'MNG', 'MENAGERE'),
    (nextval('categorie_professionnelle_id_seq'), 'MUS', 'MUSICIEN'),
    (nextval('categorie_professionnelle_id_seq'), 'NOT', 'NOTAIRE'),
    (nextval('categorie_professionnelle_id_seq'), 'OMP', 'OFFICIEN DU MINISTERE PUBLIC'),
    (nextval('categorie_professionnelle_id_seq'), 'OOO', 'SANS PROFESSION'),
    (nextval('categorie_professionnelle_id_seq'), 'OPJ', 'Officier de la police judici.'),
    (nextval('categorie_professionnelle_id_seq'), 'OUV', 'OUVRIER'),
    (nextval('categorie_professionnelle_id_seq'), 'PAT', 'PATICIEN'),
    (nextval('categorie_professionnelle_id_seq'), 'PEC', 'PECHEUR'),
    (nextval('categorie_professionnelle_id_seq'), 'PEI', 'PEINTRE'),
    (nextval('categorie_professionnelle_id_seq'), 'PHA', 'PHARMACIEN'),
    (nextval('categorie_professionnelle_id_seq'), 'PIL', 'PILOTE'),
    (nextval('categorie_professionnelle_id_seq'), 'PLO', 'PLOMBIEN'),
    (nextval('categorie_professionnelle_id_seq'), 'POL', 'POLICIER'),
    (nextval('categorie_professionnelle_id_seq'), 'PRO', 'PROFESSEUR'),
    (nextval('categorie_professionnelle_id_seq'), 'PTR', 'PETROLIER'),
    (nextval('categorie_professionnelle_id_seq'), 'REL', 'RELIGIEUX'),
    (nextval('categorie_professionnelle_id_seq'), 'SEC', 'SECRETAIRE'),
    (nextval('categorie_professionnelle_id_seq'), 'SEN', 'SENTINELLE'),
    (nextval('categorie_professionnelle_id_seq'), 'SPO', 'SPORTIF'),
    (nextval('categorie_professionnelle_id_seq'), 'TAI', 'TAILLEUR'),
    (nextval('categorie_professionnelle_id_seq'), 'TEC', 'TECHNICIEN'),
    (nextval('categorie_professionnelle_id_seq'), 'TEN', 'TENANCIER DE BAR'),
    (nextval('categorie_professionnelle_id_seq'), 'TOU', 'TOURNEUR DE CINEMA'),
    (nextval('categorie_professionnelle_id_seq'), 'TRA', 'TRANSPORTEUR'),
    (nextval('categorie_professionnelle_id_seq'), 'VEI', 'VEILLEUR'),
    (nextval('categorie_professionnelle_id_seq'), 'VEN', 'VENDEUR');