INSERT INTO gestionnaire (id, name, code) VALUES
    (nextval('gestionnaire_id_seq'), '', ''),
    (nextval('gestionnaire_id_seq'), 'KONATE LAROSSE NADEGE', '309'),
    (nextval('gestionnaire_id_seq'), 'TOURE MARIE ANGE', '313'),
    (nextval('gestionnaire_id_seq'), 'GUEYE DAMI CEDRIC JORDAN', '396'),
    (nextval('gestionnaire_id_seq'), 'MM SARR SORAYA', '310'),
    (nextval('gestionnaire_id_seq'), 'DIAWARA', '328'),
    (nextval('gestionnaire_id_seq'), 'KADIO Topé Yannick', '311'),
    (nextval('gestionnaire_id_seq'), 'TAMBOURA Taya Achérif', '312'),
    (nextval('gestionnaire_id_seq'), 'DIAWARA BOURAHIMA', '315'),
    (nextval('gestionnaire_id_seq'), 'KOUAKOU ZATCHI NINA JOELLE', '321'),
    (nextval('gestionnaire_id_seq'), 'ADAMAN COULIBALY', '302'),
    (nextval('gestionnaire_id_seq'), 'NADINE KOUAMELAN', '140'),
    (nextval('gestionnaire_id_seq'), 'TRAORE PETANKY', '322'),
    (nextval('gestionnaire_id_seq'), 'SANOGO SITA', '382'),
    (nextval('gestionnaire_id_seq'), 'KOUAME N"GUESSAN BONGO JOSEPH', '385'),
    (nextval('gestionnaire_id_seq'), 'MIEHI KOUTOHI SERGE HERVE', '386'),
    (nextval('gestionnaire_id_seq'), 'BOCOUM HAWA', '387'),
    (nextval('gestionnaire_id_seq'), 'SAISIE AUTORISATION PLAF', '150'),
    (nextval('gestionnaire_id_seq'), 'N"DRI MONELLE EPSE AHONZO', '383'),
    (nextval('gestionnaire_id_seq'), 'ZIMBRIL JOSEPH', '384'),
    (nextval('gestionnaire_id_seq'), 'KRA ALEXIS', '388'),
    (nextval('gestionnaire_id_seq'), 'BODO PHILIPPE', '389'),
    (nextval('gestionnaire_id_seq'), 'KOUAME JESSICA', '390'),
    (nextval('gestionnaire_id_seq'), 'KRA FRANCK', '391'),
    (nextval('gestionnaire_id_seq'), 'DRAMERA MARIAM', '392'),
    (nextval('gestionnaire_id_seq'), 'DOGBO RUFFIN', '393'),
    (nextval('gestionnaire_id_seq'), 'GOHOLE-BI ISAAC', '395'),
    (nextval('gestionnaire_id_seq'), 'MOUSSOKORO TOURE', '251'),
    (nextval('gestionnaire_id_seq'), 'ADJOUMANI LEATITIA', '342'),
    (nextval('gestionnaire_id_seq'), 'BAMBA BEN ADAM OLD', '343'),
    (nextval('gestionnaire_id_seq'), 'IDRISSA WELE DIALLO', '110'),
    (nextval('gestionnaire_id_seq'), 'KONE LACINA', '120'),
    (nextval('gestionnaire_id_seq'), 'DIRECTEUR FINANCIER ET COMPTAB', '130'),
    (nextval('gestionnaire_id_seq'), 'CHEF D"AGENCE', '200'),
    (nextval('gestionnaire_id_seq'), 'CHARGE DE CPTES ET EXPLOITANT', '205'),
    (nextval('gestionnaire_id_seq'), 'N"CHO HENRI HERVE WENCESLAS', '210'),
    (nextval('gestionnaire_id_seq'), 'KOUAMELAN ALLABRA ALICE', '211'),
    (nextval('gestionnaire_id_seq'), 'N"GORAN APPOLIN ALFRED', '212'),
    (nextval('gestionnaire_id_seq'), 'SIANI WOTTIEN DIEU-DONNE', '213'),
    (nextval('gestionnaire_id_seq'), 'GBA TIEMOKO RODRIGUE', '214'),
    (nextval('gestionnaire_id_seq'), 'OUATTARA KATHI ESTER', '394'),
    (nextval('gestionnaire_id_seq'), 'DIRECTION DE LA COMPTABILITE', '135'),
    (nextval('gestionnaire_id_seq'), 'MM LY FATOU', '215'),
    (nextval('gestionnaire_id_seq'), 'MICHAEL CISSE', '217'),
    (nextval('gestionnaire_id_seq'), 'FANNY', '336'),
    (nextval('gestionnaire_id_seq'), 'ERIC BOHOUA', '252'),
    (nextval('gestionnaire_id_seq'), 'MARIE LAURE EWUSSI', '301'),
    (nextval('gestionnaire_id_seq'), 'YACOUBA DIARRA', '253'),
    (nextval('gestionnaire_id_seq'), 'AMARI EDJEMS', '216'),
    (nextval('gestionnaire_id_seq'), 'SOUMAILA SAMASSI', '254'),
    (nextval('gestionnaire_id_seq'), 'YANNICK BOSSOUN', '255'),
    (nextval('gestionnaire_id_seq'), 'NANCY KOUASSI', '303'),
    (nextval('gestionnaire_id_seq'), 'PATA AWA', '304'),
    (nextval('gestionnaire_id_seq'), 'SERGE BALY', '305'),
    (nextval('gestionnaire_id_seq'), 'KOUAME JUSTE', '306'),
    (nextval('gestionnaire_id_seq'), 'KALIFALA SOUMAHORO', '307'),
    (nextval('gestionnaire_id_seq'), 'DJEA AOUONHO', '308'),
    (nextval('gestionnaire_id_seq'), 'N"GUESSAN ANDE AHOU ESTELLE', '316'),
    (nextval('gestionnaire_id_seq'), 'MME KOUADIO AHORAN', '317'),
    (nextval('gestionnaire_id_seq'), 'COULIBALY YAH SITA', '318'),
    (nextval('gestionnaire_id_seq'), 'AMON AKRE MARIETTA', '319'),
    (nextval('gestionnaire_id_seq'), 'MARC HOUPHOUET', '314'),
    (nextval('gestionnaire_id_seq'), 'KEITA HAWA CISSE', '320'),
    (nextval('gestionnaire_id_seq'), 'SEHI MAHIE NESMOND HERVE', '340'),
    (nextval('gestionnaire_id_seq'), 'KRA ALEXIS', '366'),
    (nextval('gestionnaire_id_seq'), 'KOUMBATY', '329'),
    (nextval('gestionnaire_id_seq'), 'ISMAEL KONE', '330'),
    (nextval('gestionnaire_id_seq'), 'MME YAO ROSE', '331'),
    (nextval('gestionnaire_id_seq'), 'AHIMAIN', '332'),
    (nextval('gestionnaire_id_seq'), 'ANGE KOUAME', '333'),
    (nextval('gestionnaire_id_seq'), 'COULIBALY ALASSANE', '334'),
    (nextval('gestionnaire_id_seq'), 'SORO KODANA', '335'),
    (nextval('gestionnaire_id_seq'), 'ADAMS BAMBA', '337'),
    (nextval('gestionnaire_id_seq'), 'PELEY BLEDJA EPSE ADJOUMANI', '338'),
    (nextval('gestionnaire_id_seq'), 'TOURE ASSETOU', '339'),
    (nextval('gestionnaire_id_seq'), 'MASSA WESCENSLAS', '341'),
    (nextval('gestionnaire_id_seq'), 'MME SIBY FANTA', '347'),
    (nextval('gestionnaire_id_seq'), 'TAPE ANNICK SANDRINE', '345'),
    (nextval('gestionnaire_id_seq'), 'DIALLO NABINTOU EPSE BAMBA', '346'),
    (nextval('gestionnaire_id_seq'), 'EPONON KOIKOU JEAN YVES', '348'),
    (nextval('gestionnaire_id_seq'), 'MOYA', '349'),
    (nextval('gestionnaire_id_seq'), 'MARIE LUCE KOUAME', '350'),
    (nextval('gestionnaire_id_seq'), 'KADIDIATOU S BAMBA', '351'),
    (nextval('gestionnaire_id_seq'), 'AMOUZI', '352'),
    (nextval('gestionnaire_id_seq'), 'KOUAO ANICET-GILDAS', '353'),
    (nextval('gestionnaire_id_seq'), 'KOUADIO DONATIEN', '354'),
    (nextval('gestionnaire_id_seq'), 'KOUMARE AMINATA', '355'),
    (nextval('gestionnaire_id_seq'), 'KONAN JOEL YAO', '356'),
    (nextval('gestionnaire_id_seq'), 'KABLAN KOFFI ALEXANDRE', '357'),
    (nextval('gestionnaire_id_seq'), 'AUGOU ELLA REINE', '358'),
    (nextval('gestionnaire_id_seq'), 'IBITOWA Abdoul Kader', '359'),
    (nextval('gestionnaire_id_seq'), 'ATJI ELIMANE', '360'),
    (nextval('gestionnaire_id_seq'), 'N"DIOUR Aissata', '361'),
    (nextval('gestionnaire_id_seq'), 'TOURE MOUSSOKORO', '362'),
    (nextval('gestionnaire_id_seq'), 'KONE FATOUMATA', '363'),
    (nextval('gestionnaire_id_seq'), 'KOUAME QUONAN FLORA', '364'),
    (nextval('gestionnaire_id_seq'), 'TIA GLADE JEANNE', '365'),
    (nextval('gestionnaire_id_seq'), 'KOIZAN', '367'),
    (nextval('gestionnaire_id_seq'), 'Koffi Marc KONAN', '368'),
    (nextval('gestionnaire_id_seq'), 'Mme KAHIDE TEBILI CHANCELLE', '369'),
    (nextval('gestionnaire_id_seq'), 'KASSOU Benjamin', '370'),
    (nextval('gestionnaire_id_seq'), 'GBEHOUON YVON CEDRIC-ARTHUR', '371'),
    (nextval('gestionnaire_id_seq'), 'OUATTARA FANGNARIBA ALEX', '373'),
    (nextval('gestionnaire_id_seq'), 'Mme ANVO SIALOU CARINE', '374'),
    (nextval('gestionnaire_id_seq'), 'ABBE YAYA JOSEPH', '375'),
    (nextval('gestionnaire_id_seq'), 'KRA NIAMBLEY MARC', '376'),
    (nextval('gestionnaire_id_seq'), 'DJE LOU ESTELLE', '377'),
    (nextval('gestionnaire_id_seq'), 'OULAI KAYE ELYSE-SATURNIN', '378'),
    (nextval('gestionnaire_id_seq'), 'ANZOUAN EKUE EKLABA AUDREY', '379'),
    (nextval('gestionnaire_id_seq'), 'BEHIRA KOFFI CHARLES', '380'),
    (nextval('gestionnaire_id_seq'), 'TOHOULI THIBAUT ACHILLE', '381');
