INSERT INTO profil (id, code, name)
VALUES
    (nextval('profil_id_seq'), '021', 'Personnel BDU-CI SA Retraité'),
    (nextval('profil_id_seq'), '020', 'Personnel BDU-CI SA Actif'),
    (nextval('profil_id_seq'), '023', 'Personnel BCEAO'),
    (nextval('profil_id_seq'), '027', 'Confrères Etrangers'),
    (nextval('profil_id_seq'), '028', 'Trésor Public et assimilés'),
    (nextval('profil_id_seq'), '029', 'Banque centrale et assimilés'),
    (nextval('profil_id_seq'), '034', 'Personnel BDU-CI SA Licencié'),
    (nextval('profil_id_seq'), '035', 'Personnel BDU-CI SA Démissionn'),
    (nextval('profil_id_seq'), '036', 'Personnel BDU-CI SA Décédé'),
    (nextval('profil_id_seq'), '090', 'Clients Virtuels'),
    (nextval('profil_id_seq'), '097', 'Clients Internes'),
    (nextval('profil_id_seq'), '099', 'Non Clients'),
    (nextval('profil_id_seq'), '100', 'Ambassades'),
    (nextval('profil_id_seq'), '101', 'Presidence'),
    (nextval('profil_id_seq'), '102', 'Personnel des Ambassades'),
    (nextval('profil_id_seq'), '110', 'Administrateurs BDU-CI SA'),
    (nextval('profil_id_seq'), '115', 'CONSULTANTS BDU-CI SA'),
    (nextval('profil_id_seq'), '200', 'Comptes en déshérence'),
    (nextval('profil_id_seq'), '022', 'Personnel du Groupe BDM-SA'),
    (nextval('profil_id_seq'), '012', 'CPTE COUR. ENTR BDU PREMIER'),
    (nextval('profil_id_seq'), '013', 'CPTE COUR. PARTI  BDU PREMIER'),
    (nextval('profil_id_seq'), '014', 'CPTE EPRGN.  BDU GOLD'),
    (nextval('profil_id_seq'), '052', 'Eleve Gendarme'),
    (nextval('profil_id_seq'), '055', 'Policier'),
    (nextval('profil_id_seq'), '010', 'ENTR. Cptes Courants rénumés'),
    (nextval('profil_id_seq'), '011', 'PARTIC. Cptes Courants rénumés'),
    (nextval('profil_id_seq'), '032', 'Personnel Inion Européenne'),
    (nextval('profil_id_seq'), '001', 'Clients Ordinaires Particulier'),
    (nextval('profil_id_seq'), '002', 'Clients Ordinaires Entreprises'),
    (nextval('profil_id_seq'), '003', 'Clients Ordinaires Autres'),
    (nextval('profil_id_seq'), '004', 'Clients Grands Déposants Part.'),
    (nextval('profil_id_seq'), '005', 'Clients Grands Déposants Entr.'),
    (nextval('profil_id_seq'), '006', 'Clients Grands Déposants Autre'),
    (nextval('profil_id_seq'), '007', 'Clients Gros Utilisat. Partic.'),
    (nextval('profil_id_seq'), '008', 'Clients Gros Utilisat. Entrep.'),
    (nextval('profil_id_seq'), '009', 'Clients Gros Utilisat. Autres'),
    (nextval('profil_id_seq'), '015', 'Commerçants détaillants'),
    (nextval('profil_id_seq'), '025', 'Clients Sociétés en formation'),
    (nextval('profil_id_seq'), '026', 'Confrères locaux'),
    (nextval('profil_id_seq'), '041', 'Personnel Etablissement Scolaire'),
    (nextval('profil_id_seq'), '089', 'Clients déclassés en douteux'),
    (nextval('profil_id_seq'), '103', 'Clients à accès limité'),
    (nextval('profil_id_seq'), '120', 'Actionnaires BDU-CI SA'),
    (nextval('profil_id_seq'), '050', 'Gendarme'),
    (nextval('profil_id_seq'), '051', 'Fonctionnaire'),
    (nextval('profil_id_seq'), '053', 'Salarié du Privé'),
    (nextval('profil_id_seq'), '054', 'Inter_Secu'),
    (nextval('profil_id_seq'), '056', 'Centre Medial GE'),
    (nextval('profil_id_seq'), '057', 'MUDACI'),
    (nextval('profil_id_seq'), '058', 'AGIO 1500'),
    (nextval('profil_id_seq'), '125', 'Commissaires Comptes/ BDU-CI SA'),
    (nextval('profil_id_seq'), '059', 'CIFAE'),
    (nextval('profil_id_seq'), '060', 'AGIO_2000');
